services:
  # --- PostgreSQL Database for Moodle ---
  moodle_db:
    image: postgres:17.5
    container_name: entrenai_moodle_db
    restart: unless-stopped
    ports:
      - "${MOODLE_DB_HOST_PORT:-5432}:5432" # PostgreSQL port
    volumes:
      - moodle_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${MOODLE_DB_USER:-moodle_user}
      POSTGRES_PASSWORD: ${MOODLE_DB_PASSWORD:-moodle_password}
      POSTGRES_DB: ${MOODLE_DB_NAME:-moodle_db}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    networks:
      - entrenai_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-moodle_user} -d $${POSTGRES_DB:-moodle_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Moodle Application ---
  moodle:
    image: bitnami/moodle:4.5.4
    container_name: entrenai_moodle_app
    restart: unless-stopped
    ports:
      - "${MOODLE_HOST_PORT:-8080}:8080" # Moodle app port
      - "${MOODLE_HOST_SSL_PORT:-8443}:8443" # Moodle SSL port
    volumes:
      - moodle_app_data:/bitnami/moodle
      - moodle_data_dir:/bitnami/moodledata # Moodle data directory
    environment:
      MOODLE_DATABASE_TYPE: pgsql
      MOODLE_DATABASE_HOST: moodle_db
      MOODLE_DATABASE_PORT_NUMBER: 5432
      MOODLE_DATABASE_USER: ${MOODLE_DB_USER:-moodle_user}
      MOODLE_DATABASE_PASSWORD: ${MOODLE_DB_PASSWORD:-moodle_password}
      MOODLE_DATABASE_NAME: ${MOODLE_DB_NAME:-moodle_db}
      MOODLE_USERNAME: ${MOODLE_USERNAME:-admin}
      MOODLE_PASSWORD: ${MOODLE_PASSWORD:-admin_password}
      MOODLE_EMAIL: ${MOODLE_EMAIL:-admin@example.com}
      MOODLE_SITE_NAME: ${MOODLE_SITENAME:-Entrenai Moodle}
      MOODLE_REVERSEPROXY: ${MOODLE_REVERSEPROXY:-no}
      ALLOW_EMPTY_PASSWORD: 'no'
    depends_on:
      moodle_db:
        condition: service_healthy
    networks:
      - entrenai_net

  # --- Qdrant Vector Database ---
  qdrant:
    image: qdrant/qdrant:v1.14.0
    container_name: entrenai_qdrant
    restart: unless-stopped
    ports:
      - "${QDRANT_HOST_HTTP_PORT:-6333}:6333" # HTTP port
      - "${QDRANT_HOST_GRPC_PORT:-6334}:6334" # gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
    # Example for API key (uncomment and set QDRANT_API_KEY in .env if needed)
    # environment:
    #   QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    networks:
      - entrenai_net

  # --- Ollama LLM Server ---
  ollama:
    image: ollama/ollama:0.6.8
    container_name: entrenai_ollama
    restart: unless-stopped
    ports:
      - "${OLLAMA_HOST_PORT:-11434}:11434"
    volumes:
      - ollama_models:/root/.ollama # Persist models
    # To enable GPU support (example for NVIDIA, ensure drivers are installed on host):
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1 # or 'all'
    #           capabilities: [gpu]
    networks:
      - entrenai_net

  # --- PostgreSQL Database for N8N ---
  n8n_db:
    image: postgres:17.5
    container_name: entrenai_n8n_db
    restart: unless-stopped
    volumes:
      - n8n_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${N8N_DB_USER:-n8n_user}
      POSTGRES_PASSWORD: ${N8N_DB_PASSWORD:-n8n_password}
      POSTGRES_DB: ${N8N_DB_NAME:-n8n_db}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    networks:
      - entrenai_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-n8n_user} -d $${POSTGRES_DB:-n8n_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- N8N Workflow Automation ---
  n8n:
    image: n8nio/n8n:1.91.3
    container_name: entrenai_n8n_app
    restart: unless-stopped
    ports:
      - "${N8N_HOST_PORT:-5678}:5678"
    volumes:
      - n8n_app_data:/home/node/.n8n
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: n8n_db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${N8N_DB_NAME:-n8n_db}
      DB_POSTGRESDB_USER: ${N8N_DB_USER:-n8n_user}
      DB_POSTGRESDB_PASSWORD: ${N8N_DB_PASSWORD:-n8n_password}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY:-a_very_secure_random_string_for_n8n} # CHANGE THIS IN .env!
      N8N_EMAIL_MODE: smtp # Placeholder, can be configured later if email sending is needed
      N8N_HOST: ${N8N_HOST_DOMAIN:-localhost} # Set to your domain if N8N is publicly accessible
      WEBHOOK_URL: ${N8N_WEBHOOK_URL:-http://localhost:5678} # URL N8N uses for its webhooks
      # GENERIC_TIMEZONE: America/Argentina/Buenos_Aires # Set your timezone
    depends_on:
      n8n_db:
        condition: service_healthy
    networks:
      - entrenai_net

volumes:
  moodle_db_data:
    driver: local
  moodle_app_data:
    driver: local
  moodle_data_dir:
    driver: local
  qdrant_data:
    driver: local
  ollama_models:
    driver: local
  n8n_db_data:
    driver: local
  n8n_app_data:
    driver: local

networks:
  entrenai_net:
    driver: bridge
