apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: lucas-garcia-entrenai-no-borrar
type: Opaque
data:
  N8N_API_KEY: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXhpT2lKS1ZFWkNJbjAuZXlKemRXSWlPaUpoTVVSOGJqVmlNaS1tWXpRMExUUTJNRFVpT2lKaE1tSXlZekkyTnpFaUxDSmliR3hpT2lKb2I4biIsImF1ZCI6InB1YmxpYy1hcGkiLCJpYXQiOjE3NDcwODA2OTF9Lk9YVlVMSGVFSG5fQjdTYmlzeHZBVnpBWW4wd3M4WTAxcDVqYUZpMFphM1U=
  N8N_ENCRYPTION_KEY: YV92ZXJ5X3NlY3VyZV9yYW5kb21fc3RyaW5nX2Zvcl9uOG4=
