apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: lucas-garcia-entrenai-no-borrar
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
