apiVersion: v1
kind: Secret
metadata:
  name: vector-db-secret
  namespace: lucas-garcia-entrenai-no-borrar
type: Opaque
data:
  POSTGRES_USER: cGdrZWN0b3JfdXNlcg== # pgvector_user
  POSTGRES_PASSWORD: cGdrZWN0b3JfcGFzc3dvcmQ= # pgvector_password
