apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vector-db
  namespace: lucas-garcia-entrenai-no-borrar
spec:
  serviceName: "vector-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: vector-db
  template:
    metadata:
      labels:
        app: vector-db
    spec:
      containers:
      - name: postgres
        image: pgvector/pgvector:0.8.0-pg17
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: vector-db-secret
        - configMapRef:
            name: vector-db-config
        volumeMounts:
        - name: vector-db-storage
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
  volumeClaimTemplates:
  - metadata:
      name: vector-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
