apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: lucas-garcia-entrenai-no-borrar
type: Opaque
data:
  GEMINI_API_KEY: QUl6YVN5QXpINVF0VjFxTjZ2Wk5iUVRPOEVFMUN0cm8zOW84aWlN
  N8N_API_KEY: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXhpT2lKS1ZFWkNJbjAuZXlKemRXSWlPaUpoTVVSOGJqVmlNaS1tWXpRMExUUTJNRFVpT2lKaE1tSXlZekkyTnpFaUxDSmliR3hpT2lKb2I4biIsImF1ZCI6InB1YmxpYy1hcGkiLCJpYXQiOjE3NDcwODA2OTF9Lk9YVlVMSGVFSG5fQjdTYmlzeHZBVnpBWW4wd3M4WTAxcDVqYUZpMFphM1U=
  MOODLE_TOKEN: NGZkZmM3OWE4OGFkNmQwZjc5YTlhMmU4M2M4ZTE0MTk=
