apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: lucas-garcia-entrenai-no-borrar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-app
        image: luxor12354/tesis-entrenai:api
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: fastapi-config
        - secretRef:
            name: fastapi-secret
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: vector-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vector-db-secret
              key: POSTGRES_PASSWORD
