apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: lucas-garcia-entrenai-no-borrar
data:
  # App
  LOG_LEVEL: "INFO"
  FASTAPI_HOST: "0.0.0.0"
  FASTAPI_PORT: "8000"
  APP_ENV: "kubernetes"
  # Database
  DATABASE_URL: "postgresql+psycopg2://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@vector-db-service:5432/pgvector_db"
  PGVECTOR_COLLECTION_PREFIX: "entrenai_course_"
  DEFAULT_VECTOR_SIZE: "1024"
  # Celery
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
  # Moodle
  MOODLE_URL: "https://kvrtkc31-8080.brs.devtunnels.ms/" # External URL
  MOODLE_COURSE_FOLDER_NAME: "Entrenai Documents"
  MOODLE_REFRESH_LINK_NAME: "Refresh Entrenai IA"
  MOODLE_CHAT_LINK_NAME: "Chat con Entrenai IA"
  MOODLE_DEFAULT_TEACHER_ID: "2"
  # AI Provider
  AI_PROVIDER: "ollama"
  # Ollama
  OLLAMA_HOST: "http://172.16.16.76:11434"
  OLLAMA_EMBEDDING_MODEL: "snowflake-arctic-embed2" # Example, choose a suitable model available in your Ollama
  OLLAMA_MARKDOWN_MODEL: "llama3.2:1b" # Example, for transforming to Markdown
  OLLAMA_QA_MODEL: "llama3.2:1b" # Example, for RAG question answering
  OLLAMA_CONTEXT_MODEL: "llama3.2:1b" # Example, for adding context to chunks
  # Gemini
  GEMINI_EMBEDDING_MODEL: "gemini-embedding-exp-03-07"
  GEMINI_TEXT_MODEL: "gemini-1.5-flash-preview-05-20"
  GEMINI_VISION_MODEL: "gemini-1.5-pro-vision"
  GEMINI_SAFETY_SETTINGS_ENABLED: "True"
  GEMINI_EMBEDDING_DIMENSION: "1024"
  # N8N
  N8N_URL: "http://n8n-service:5678"
  N8N_WEBHOOK_URL: "https://n8n-ucas-garcia-entrenai-no-borrar.my.kube.um.edu.ar"
  N8N_WORKFLOW_JSON_PATH: "./src/entrenai/n8n_workflow.json"
