services:
  # --- PostgreSQL Database for Moodle ---
  moodle_db:
    image: postgres:17.5
    container_name: entrenai_moodle_db
    ports:
      - "${MOODLE_DB_HOST_PORT}:5432"
    volumes:
      - moodle_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${MOODLE_DB_USER}
      POSTGRES_PASSWORD: ${MOODLE_DB_PASSWORD}
      POSTGRES_DB: ${MOODLE_DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - entrenai_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${MOODLE_DB_USER} -d $${MOODLE_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Moodle Application ---
  moodle:
    image: bitnami/moodle:4.5.4
    container_name: entrenai_moodle_app
    ports:
      - "${MOODLE_HOST_PORT}:8080"
      - "${MOODLE_HOST_SSL_PORT}:8443"
    volumes:
      - moodle_app_volume:/bitnami/moodle
      - moodle_data_volume:/bitnami/moodledata
    environment:
      MOODLE_DATABASE_TYPE: pgsql
      MOODLE_DATABASE_HOST: moodle_db
      MOODLE_DATABASE_PORT_NUMBER: 5432
      MOODLE_DATABASE_USER: ${MOODLE_DB_USER}
      MOODLE_DATABASE_PASSWORD: ${MOODLE_DB_PASSWORD}
      MOODLE_DATABASE_NAME: ${MOODLE_DB_NAME}
      MOODLE_USERNAME: ${MOODLE_USERNAME}
      MOODLE_PASSWORD: ${MOODLE_PASSWORD}
    depends_on:
      moodle_db:
        condition: service_healthy
    networks:
      - entrenai_network

volumes:
  moodle_db_volume:
  moodle_app_volume:
  moodle_data_volume:

networks:
  entrenai_network:
    driver: bridge