version: '3.8'

services:
  # PostgreSQL con pgvector
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: entrenai
      POSTGRES_USER: entrenai
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U entrenai -d entrenai"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Ollama (opcional)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

  # N8N (opcional)
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n

  # EntrenAI API
  entrenai:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=entrenai
      - DB_USER=entrenai
      - DB_PASSWORD=password
      - REDIS_URL=redis://redis:6379
      - OLLAMA_HOST=http://ollama:11434
      - N8N_URL=http://n8n:5678
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./src:/app/src
    command: uvicorn src.entrenai.api.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data:
  ollama_data:
  n8n_data:
