apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-secret
  namespace: lucas-garcia-entrenai-no-borrar
type: Opaque
data:
  POSTGRES_USER: bjhuX3VzZXI= # n8n_user
  POSTGRES_PASSWORD: bjhuX3Bhc3N3b3Jk # n8n_password
