apiVersion: v1
kind: Service
metadata:
  name: n8n-db-service
  namespace: lucas-garcia-entrenai-no-borrar
spec:
  selector:
    app: n8n-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  clusterIP: None # Headless service for StatefulSet
