version: '3.8'

services:
  app:
    build: .
    command: uvicorn entrenai_refactor.api.principal:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A entrenai_refactor.celery.aplicacion_celery.app worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
  redis:
    image: redis:7
    ports:
      - "6379:6379" 