FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.celery.txt
CMD ["celery", "-A", "entrenai_refactor.celery.aplicacion_celery.app", "worker", "--loglevel=info"] 